service: serverless-websocket-nest

frameworkVersion: '3'

plugins:
  - serverless-offline

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  region: ${env:REGION}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${env:USERS_TABLE}
            - arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${env:USER_CONNECTIONS_TABLE}
            - arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${env:CHAT_ROOMS_TABLE}
            - arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${env:CHATS_TABLE}
  environment:
    NODE_ENV: ${param:NODE_ENV, 'development'}

package:
  include:
    - dist/**/*
    - node_modules/**/*
  exclude:
    - terraform/**/*
    - src/**/*

functions:
  # AWS Lambda Function
  mainHandler:
    handler: dist/handler/lambda.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'

custom:
  # Serverless Offline Plugin
  serverless-offline:
    httpPort: 3500
    websocketPort: 3501